### ISSUE TITLE
Can't launch Beta

### ISSUE THREAD

**Issue by 3400877** [flathub/com.valvesoftware.Steam#1111]
I installed Steam through the Beta branch and I get the following error message:

```
$ flatpak run com.valvesoftware.Steam//beta
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
ERROR:root:~/.steam/root isn't a symlink to an existing directory, cannot determine current prefix
INFO:root:Will set XDG dirs prefix to /home/caron/.var/app/com.valvesoftware.Steam
INFO:migration:Copying /home/caron/.var/app/com.valvesoftware.Steam/.local/share to /home/caron/.var/app/com.valvesoftware.Steam/.local/share.bak, ignoring {'Steam'}
Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.10/site-packages/steam_wrapper.py", line 480, in main
    should_restart += migrate_data(current_info, xdg_dirs_prefix)
  File "/app/lib/python3.10/site-packages/steam_wrapper.py", line 332, in migrate_data
    should_restart = migrator.apply()
  File "/app/lib/python3.10/site-packages/steam_wrapper.py", line 284, in apply
    self.do_migrate()
  File "/app/lib/python3.10/site-packages/steam_wrapper.py", line 244, in do_migrate
    self._copytree(self.target, self.target_backup)
  File "/app/lib/python3.10/site-packages/steam_wrapper.py", line 237, in _copytree
    shutil.copytree(src, dst, symlinks=True, ignore=self.file_ignorer, dirs_exist_ok=True)
  File "/usr/lib/python3.10/shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.10/shutil.py", line 453, in _copytree
    ignored_names = ignore(os.fspath(src), [x.name for x in entries])
  File "/app/lib/python3.10/site-packages/steam_wrapper.py", line 206, in __call__
    os.path.join(src, ignored_pat)):
NameError: name 'src' is not defined
```

**Comment by nanonyme** [comment]
Oops! Good catch, this is actually pretty bad.

**Comment by nanonyme** [comment]
Do you have time to confirm that beta now works for you?

**Comment by 3400877** [comment]
I tested it, and it's working now.

**Comment by nanonyme** [comment]
Great. I aim to soon release beta to stable after which beta will start using freedesktop-sdk 23.08beta.
