### ISSUE TITLE
Steam crashes on glXChooseVisual

### ISSUE THREAD

**Issue by majkrzak** [flathub/com.valvesoftware.Steam#1309]
**Distribution name and version where applicable**
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```
```
OpenGL renderer string: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 17.0.6, DRM 3.57, 6.9.1-arch1-2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.0.7-arch1.3
```

**Flatpak info**
```
~> flatpak --gl-drivers
default
host
~> flatpak --version 
Flatpak 1.15.8
```

**Problem description**
After the update to 
```
Valve Corporation               com.valvesoftware.Steam                                      1.0.0.79           stable                system
Freedesktop Platform            org.freedesktop.Platform                                     23.08.18           23.08                 system
i386                            org.freedesktop.Platform.Compat.i386                                            23.08                 system
Mesa                            org.freedesktop.Platform.GL.default                          24.0.7             23.08                 system
Mesa (Extra)                    org.freedesktop.Platform.GL.default                          24.0.7             23.08-extra           system
Mesa                            org.freedesktop.Platform.GL32.default                        24.0.7             23.08                 system
Mesa (Extra)                    org.freedesktop.Platform.GL32.default                        24.0.7             23.08-extra           system
```
Steam start  to crash with:
```
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting
```

**Does this issue reproduce with native Steam**
Have not tested

**Comment by KriiXOne** [comment]
Can confirm this issue after the last updates, together with issues: https://github.com/flathub/com.valvesoftware.Steam/issues/1306 https://github.com/flathub/com.valvesoftware.Steam/issues/1300 https://github.com/flathub/com.valvesoftware.Steam/issues/1298 also happening very frequently.

**Comment by majkrzak** [comment]
Steam got back among the livings after "updating" to
```
Freedesktop Platform            org.freedesktop.Platform                                     23.08.17           23.08                 system
```
Apparently the `23.08.18` got reverted. 
`flatpak update` failed with the downgrade warning, but managed to workaround it by:
```
flatpak uninstall org.freedesktop.Platform --force-remove
flatpak install org.freedesktop.Platform
```

**Comment by smr99** [comment]
Same problem on Debian "sid" with the official Steam deb package.

$ steam
/home/steve/.local/share/Steam/steam.sh: line 186: VERSION_ID: unbound variable
Traceback (most recent call last):
  File "/usr/bin/steamdeps", line 1051, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/steamdeps", line 947, in main
    nvidia_packages = expected_nvidia_packages()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/steamdeps", line 290, in expected_nvidia_packages
    update_installed_packages(nvidia_packages_to_check)
  File "/usr/bin/steamdeps", line 674, in update_installed_packages
    packages[name].set_installed(match.group(2))
    ~~~~~~~~^^^^^^
KeyError: 'nvidia-alternative:i386:i386'
/home/steve/.local/share/Steam/steam.sh: line 186: VERSION_ID: unbound variable
steam.sh[26779]: Running Steam on debian  64-bit
/home/steve/.local/share/Steam/steam.sh: line 186: VERSION_ID: unbound variable
steam.sh[26779]: STEAM_RUNTIME is enabled automatically
setup.sh[26932]: Steam runtime environment up-to-date!
steam.sh[26779]: Steam client's requirements are satisfied
06/01 18:19:38 minidumps folder is set to /tmp/dumps
06/01 18:19:38 Init: Installing breakpad exception handler for appid(steam)/version(1717207813)/tid(26992)
[2024-06-01 18:19:38] Startup - updater built May 31 2024 21:16:24
[2024-06-01 18:19:38] Startup - Steam Client launched with: '/home/steve/.local/share/Steam/ubuntu12_32/steam' '-srt-logger-opened'
[2024-06-01 18:19:38] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2024-06-01 18:19:38] Loading cached metrics from disk (/home/steve/.local/share/Steam/package/steam_client_metrics.bin)
[2024-06-01 18:19:38] Using the following download hosts for Public, Realm steamglobal
[2024-06-01 18:19:38] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-06-01 18:19:38] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-06-01 18:19:38] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-06-01 18:19:38] Checking for update on startup
[2024-06-01 18:19:38] Checking for available updates...
[2024-06-01 18:19:38] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_publicbeta_ubuntu12
[2024-06-01 18:19:38] Manifest download: send request
[2024-06-01 18:19:38] Manifest download: waiting for download to finish
[2024-06-01 18:19:38] Manifest download: finished
[2024-06-01 18:19:38] Download skipped: /steam_client_publicbeta_ubuntu12 version 1717207813, installed version 1717207813, existing pending version 0
[2024-06-01 18:19:38] Nothing to do
[2024-06-01 18:19:38] Verifying installation...
[2024-06-01 18:19:38] Performing checksum verification of executable files
[2024-06-01 18:19:39] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/steve/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf5fe06b0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf5fdef70
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting
06/01 18:19:40 Init: Installing breakpad exception handler for appid(steam)/version(1717207813)/tid(26992)
assert_20240601181940_8.dmp[27063]: Uploading dump (out-of-process)
/tmp/dumps/assert_20240601181940_8.dmp
steve@riemann:~/MachineLearning$ assert_20240601181940_8.dmp[27063]: Finished uploading minidump (out-of-process): success = yes
assert_20240601181940_8.dmp[27063]: response: CrashID=bp-fc349759-da1d-41ae-bc28-37b902240601
assert_20240601181940_8.dmp[27063]: file ''/tmp/dumps/assert_20240601181940_8.dmp'', upload yes: ''CrashID=bp-fc349759-da1d-41ae-bc28-37b902240601''

**Comment by smr99** [comment]
Happily installing package nvidia-alternative (which removed nvidia-alternative:i386) brought the system into working order again.
