### ISSUE TITLE
[Intel] The Stanley Parable doesn't work

### ISSUE THREAD

**Issue by jjardon** [flathub/com.valvesoftware.Steam#18]
Logs:

```
Game update: AppID 221910 "The Stanley Parable", ProcID 217, IP 0.0.0.0:0
>>> Adding process 217 for game ID 221910
GameAction [AppID 221910, ActionID 6] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 219 != 218, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
GameAction [AppID 221910, ActionID 6] : LaunchApp changed task to Completed with ""
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
>>> Adding process 218 for game ID 221910
>>> Adding process 220 for game ID 221910
>>> Adding process 221 for game ID 221910
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
>>> Adding process 222 for game ID 221910
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

**Comment by nanonyme** [comment]
Does this issue still persist? Which version of flatpak was used? How was Steam installed?

**Comment by jjardon** [comment]
Tested today again: It works!

**Comment by jjardon** [comment]
Still no luck :(
- flatpak version: 0.9.1
- I installed it from the link in flathub page (through GNOME Software)

**Comment by nanonyme** [comment]
Could you try running "flatpak update" to see if this is the classic problem of having too old version of Gnome Software that doesn't handle dependencies correctly?

**Comment by jjardon** [comment]
@nanonyme I have run "flatpak update" but exactly same problem

**Comment by nanonyme** [comment]
What about now? The entire runtime was just updated...

**Comment by jjardon** [comment]
@nanonyme updated today; exactly same issue:
```
GameAction [AppID 221910, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask: 70
Game update: AppID 221910 "", ProcID 271, IP 0.0.0.0:0
>>> Adding process 271 for game ID 221910
GameAction [AppID 221910, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 273 != 272, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 221910, ActionID 1] : LaunchApp changed task to Completed with ""
>>> Adding process 272 for game ID 221910
ERROR: ld.so: object '/home/jjardon/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
SDL video target is 'x11'

Failed to create GL context: Unable to make GL context current
>>> Adding process 274 for game ID 221910
>>> Adding process 275 for game ID 221910
>>> Adding process 276 for game ID 221910
Game removed: AppID 221910 "", ProcID 271 
No cached sticky mapping in ActivateActionSet.
```

**Comment by nanonyme** [comment]
Interresting. Googling around hints that you can hit libstdc++ incompatibilities with Intel driver. Does the game happen to ship a copy?

**Comment by nanonyme** [comment]
(all in all, listing libraries inside game installation directory might be make sense)

**Comment by jjardon** [comment]
@nanonyme you are right:
```
$ ls -l /home/jjardon/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/The\ Stanley\ Parable/bin/ | grep "\.so"
-rwxr-xr-x 1 jjardon users   704243 Aug 14 17:31 bsppack.so
-rwxr-xr-x 1 jjardon users   426185 Aug 14 17:31 crashhandler.so
-rwxr-xr-x 1 jjardon users   644664 Aug 14 17:31 datacache.so
-rwxr-xr-x 1 jjardon users   832530 Aug 14 17:31 dedicated.so
-rwxr-xr-x 1 jjardon users 10269569 Aug 14 17:31 engine.so
-rwxr-xr-x 1 jjardon users   746899 Aug 14 17:31 filesystem_stdio.so
-rwxr-xr-x 1 jjardon users   220886 Aug 14 17:31 inputsystem.so
-rwxr-xr-x 1 jjardon users   346844 Aug 14 17:31 launcher.so
-rwxr-xr-x 1 jjardon users  1446045 Aug 14 17:31 libMiles.so
-rwxr-xr-x 1 jjardon users   923556 Aug 14 17:31 libSDL2-2.0.so.0
-rwxr-xr-x 1 jjardon users  3769939 Aug 14 17:31 libstdc++.so.6
-rwxr-xr-x 1 jjardon users   595711 Aug 14 17:31 libsteam_api_linux.so
-rwxr-xr-x 1 jjardon users    66598 Aug 14 17:31 libsteam_api.so
-rwxr-xr-x 1 jjardon users  4217996 Aug 14 17:31 libsteam.so
-rwxr-xr-x 1 jjardon users   968800 Aug 14 17:31 libtcmalloc_minimal.so.4
-rwxr-xr-x 1 jjardon users   176777 Aug 14 17:31 libtier0.so
-rwxr-xr-x 1 jjardon users   685855 Aug 14 17:31 libtogl.so
-rwxr-xr-x 1 jjardon users   297644 Aug 14 17:31 libvstdlib.so
-rwxr-xr-x 1 jjardon users   257137 Aug 14 17:31 localize.so
-rwxr-xr-x 1 jjardon users  1415575 Aug 14 17:31 materialsystem.so
-rwxr-xr-x 1 jjardon users  2728156 Aug 14 17:31 puzzlemaker_dll.so
-rwxr-xr-x 1 jjardon users   120090 Aug 14 17:31 scenefilecache.so
-rwxr-xr-x 1 jjardon users   972637 Aug 14 17:31 shaderapidx9.so
-rwxr-xr-x 1 jjardon users   156217 Aug 14 17:31 shaderapiempty.so
-rwxr-xr-x 1 jjardon users   292381 Aug 14 17:31 soundemittersystem.so
-rwxr-xr-x 1 jjardon users  1016470 Aug 14 17:31 stdshader_dx9.so
-rwxr-xr-x 1 jjardon users   909542 Aug 14 17:31 studiorender.so
-rwxr-xr-x 1 jjardon users   806815 Aug 14 17:31 valve_avi.so
-rwxr-xr-x 1 jjardon users   120537 Aug 14 17:31 vaudio_miles.so
-rwxr-xr-x 1 jjardon users   145057 Aug 14 17:31 vaudio_speex.so
-rwxr-xr-x 1 jjardon users   412416 Aug 14 17:31 vgui2-mine.so
-rwxr-xr-x 1 jjardon users   412416 Aug 14 17:31 vgui2.so
-rwxr-xr-x 1 jjardon users  1849297 Aug 14 17:31 vguimatsurface.so
-rwxr-xr-x 1 jjardon users  1830623 Aug 14 17:31 vphysics.so
-rwxr-xr-x 1 jjardon users  1381192 Aug 14 17:31 vrad_dll.so
-rwxr-xr-x 1 jjardon users   841698 Aug 14 17:31 vscript.so
-rwxr-xr-x 1 jjardon users   654652 Aug 14 17:31 vvis_dll.so
```
Removing libstdc++.so.6 and libSDL2-2.0.so.0 fixed the issue

**Comment by nanonyme** [comment]
@valentindavid looks like another game that would benefit of the blacklisting feature

**Comment by nanonyme** [comment]
@jjardon could you by the way check if there's a launcher script and if so, whether it's bash?

**Comment by nanonyme** [comment]
So. I'd need the name of the game executable here too.

**Comment by valentindavid** [comment]
I have tried to set up the library filters correctly. But I have an error starting the game. A crash with stack:

```
#0  0xe89b802d in ?? () from /home/valentin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/The Stanley Parable/thestanleyparable/bin/matchmaking.so
#1  0xe89bad41 in ?? () from /home/valentin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/The Stanley Parable/thestanleyparable/bin/matchmaking.so
#2  0xe89a5d54 in ?? () from /home/valentin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/The Stanley Parable/thestanleyparable/bin/matchmaking.so
#3  0xead835cd in ?? () from /home/valentin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/The Stanley Parable/bin/engine.so
#4  0xead84844 in ?? () from /home/valentin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/The Stanley Parable/bin/engine.so
#5  0xead848c9 in ?? () from /home/valentin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/The Stanley Parable/bin/engine.so
#6  0xead19167 in ?? () from /home/valentin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/The Stanley Parable/bin/engine.so
#7  0xf777ac00 in ?? () from bin/launcher.so
#8  0xf777ac00 in ?? () from bin/launcher.so
```

This also happens when removing the libraries manually which was reported as working. So it seems unrelated, but I cannot test the configuration.

**Comment by nanonyme** [comment]
Could someone test this again?

**Comment by Lyle-Tafoya** [comment]
This game works out of the box for me, but I never had the opportunity to test it when others were reporting crashes.

**Comment by neingeist** [comment]
I came here because I have this bug with "The Stanley Parable Demo" (Demo!). However, the game itself (not the Demo) runs fine.
