### ISSUE TITLE
Reinstalling Steam problematic

### ISSUE THREAD

**Issue by jadbox** [flathub/com.valvesoftware.Steam#222]
Scenario:

1. Had Stream installed in another location using `flatpak --installation=X install ...`.
2. Removed Steam from separate installation
3. Installing Steam regularly (without `--installation=X`) and it will not start (see below error)
3a. trying `--system` or `--user` does not change the issue

flatpak run com.valvesoftware.Steam 
```
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Relocating /home/jdunlap/.var/app/com.valvesoftware.Steam/config/user-dirs.dirs to .config/user-dirs.dirs
Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 11, in <module>
    load_entry_point('steam-wrapper==1.0.0', 'console_scripts', 'steam-wrapper')()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 240, in main
    mesa_shader_workaround()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 51, in mesa_shader_workaround
    elif read_flatpak_info(current) != read_flatpak_info(FLATPAK_INFO):
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 26, in read_flatpak_info
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jdunlap/.var/app/com.valvesoftware.Steam/.config/.flatpak-info'
```

I've the trick in this issue https://github.com/flathub/com.valvesoftware.Steam/issues/155 by: `touch ~/.var/app/com.valvesoftware.Steam/config/.flatpak-info` I get the below issue:
```
Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 11, in <module>
    load_entry_point('steam-wrapper==1.0.0', 'console_scripts', 'steam-wrapper')()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 240, in main
    mesa_shader_workaround()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 51, in mesa_shader_workaround
    elif read_flatpak_info(current) != read_flatpak_info(FLATPAK_INFO):
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 29, in read_flatpak_info
    "flatpak-version": flatpak_info.get("Instance", "flatpak-version"),
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Instance'
```
------------
uname -r
`4.17.19-200.fc28.x86_64`
Fedora 28

flatpak --version
`Flatpak 1.0.1`

flatpak list
```
Ref                                                    Options       
com.skype.Client/x86_64/stable                         system,current
com.valvesoftware.Steam/x86_64/stable                  system,current
org.freedesktop.Platform.Compat.i386/x86_64/18.08      system,runtime
org.freedesktop.Platform.GL.nvidia-396-54/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL32.nvidia-396-54/x86_64/1.4 system,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08      system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6             system,runtime
org.freedesktop.Platform.html5-codecs/x86_64/18.08     system,runtime
org.freedesktop.Platform/x86_64/1.6                    system,runtime
org.freedesktop.Platform/x86_64/18.08                  system,runtime
```
flatpak info com.valvesoftware.Steam
```
Ref: app/com.valvesoftware.Steam/x86_64/stable
ID: com.valvesoftware.Steam
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-09-10 21:56:56 +0000
Subject: Add link to FAQ as the first thing (e225bdcc)
Commit: 1ab2e58c07d1378ef2703f6bd555ff6dd68ca9667659bd0a607c4177eeeef856
Parent: 694506e7674cec455424a4fabf84f7e05ed703e7660413672b52ce560563ded5
Location: /var/lib/flatpak/app/com.valvesoftware.Steam/x86_64/stable/1ab2e58c07d1378ef2703f6bd555ff6dd68ca9667659bd0a607c4177eeeef856
Installed size: 15.4 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08
```

**Comment by nanonyme** [comment]
This is a regression caused by ini file handling changes done yesterday and not related to #155.

**Comment by nanonyme** [comment]
https://flathub.org/builds/#/builders/2/builds/4377

**Comment by nanonyme** [comment]
Once #208 is done, relevant code can be completely removed
