### ISSUE TITLE
Prey 2017 memory issue  0x00000000000000

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.valvesoftware.Steam#645]
**Game information**
Prey 2017
Arkane Studios

**Distribution name and version where applicable**
```
Fedora release 33 (Thirty Three)
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 33 (Thirty Three)
Fedora release 33 (Thirty Three)
cpe:/o:fedoraproject:fedora:33
```

**Flatpak info**
```
Flatpak 1.8.2
nvidia-455-28
default
host
```

**Problem description**
- Configure Prey 2017 to use Proton 5.0-9
- Starting a new Singleplayer game
- ```Attempt to read from address 0x0000000000000000 The memory could be "read"```

**Does this issue reproduce with native Steam**
No, native Steam works.

**Comment by nanonyme** [comment]
So in other words probably NULL pointer usage.

**Comment by Eonfge** [comment]
## Logging
```
Traceback (most recent call last):
  File "/home/kevin/.local/share/Steam/steamapps/common/Proton 5.0/proton", line 707, in <module>
    g_session.run()
  File "/home/kevin/.local/share/Steam/steamapps/common/Proton 5.0/proton", line 675, in run
    self.run_proc([g_proton.wine_bin, "steam"] + sys.argv[2:] + self.cmdlineappend)
  File "/home/kevin/.local/share/Steam/steamapps/common/Proton 5.0/proton", line 667, in run_proc
    subprocess.call(args, env=local_env, stderr=self.log_file, stdout=self.log_file)
  File "/usr/lib/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
pid 379 != 378, skipping destruction (fork without exec?)
Game removed: AppID 480490 "", ProcID 420 

```
[output.log](https://github.com/flathub/com.valvesoftware.Steam/files/5489060/output.log)

**Comment by gasinvein** [comment]
@Eonfge Run the game with `PROTON_LOG=1` env var, and look for the log file in `~/.var/app/com.valvesoftware.Steam/steam-480490.log`.
BTW, does it work with Proton 5.13?

**Comment by Eonfge** [comment]
I've not tested it with Proton 5.13. I know that the mainline proton 5.13 doesn't work with Flatpak, and I didn't want to introduce any extra variables to the test.

```
======================
Proton: 1603141982 proton-5.0-10b
SteamGameId: 480490
Command: ['/home/kevin/.local/share/Steam/steamapps/common/Prey/Binaries/Danielle/x64/Release/Prey.exe']
Options: {'wined3d', 'forcelgadd'}
======================
```
[Full log: steam-480490.log](https://github.com/flathub/com.valvesoftware.Steam/files/5511623/steam-480490.log)

**Comment by gasinvein** [comment]
Hmm, reports on [protondb](https://www.protondb.com/app/480490) suggest that the game randomly crashes with error like this for some users, and it might even affect windows users as well.

**Comment by Eonfge** [comment]
Weird part is. I finished the game already twice. I have over 80 hours on it, all played on Linux. I even submitted a previous protondb report, praising the game. Resetting the prefix, checking the game cache, all to no avail... Since it does still work for me without Proton, I figured it was worth reporting.

**Comment by Eonfge** [comment]
I know it's not much of a workaround, but if I try the Flatpak build of Proton GE, the issues I've had do not occur.

```
[kevin@kevin-at-fedora ~]$ flatpak info com.valvesoftware.Steam.CompatibilityTool.Proton-GE 

Proton-GE (community build) - Latest Proton-GE version built on the Flatpak
Freedesktop SDK

          ID: com.valvesoftware.Steam.CompatibilityTool.Proton-GE
         Ref: runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.0-GE-1
     License: BSD-3-Clause and LGPL-2.1 and zlib-acknowledgement and Zlib and OFL-1.1 and MIT and MPL-2.0 and LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1.3 GB

      Commit: a19edb32d3ddb63f824a1afacdd073881313a1dc0e65007fcb2a089513ddcfb6
      Parent: 4da3091a96ed29ba60916a1cf0f9db8b24661abeb9a0b3ae5145a3f7e0536c98
     Subject: gst-plugins-ugly: fix bad value in config opts (2480f836)
        Date: 2021-01-18 14:10:38 +0000
```
