### ISSUE TITLE
Project Zomboid not start

### ISSUE THREAD

**Issue by hmsintrepide** [flathub/com.valvesoftware.Steam#67]
This game doesn't open any window and steam report it as closed
I use Fedora 27 with default and rpmfusion repos
R7 1800X with RX Vega 56

I buy it on GOG and install it without flatpak and the game work fine

> [quentin@quentin-pc Téléchargements]$ uname -a
Linux quentin-pc 4.15.4-300.fc27.x86_64 #1 SMP Mon Feb 19 23:31:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[quentin@quentin-pc Téléchargements]$ flatpak list
Ref                                              Options       
com.valvesoftware.Steam/x86_64/stable            system,current
org.freedesktop.Platform.Compat32/x86_64/1.6     system,runtime
org.freedesktop.Platform.GL.default/x86_64/1.6   system,runtime
org.freedesktop.Platform.GL32.default/x86_64/1.6 system,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6  system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6       system,runtime
org.freedesktop.Platform/x86_64/1.6              system,runtime
[quentin@quentin-pc Téléchargements]$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX Vega (VEGA10 / DRM 3.23.0 / 4.15.4-300.fc27.x86_64, LLVM 5.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.3.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.3.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:

```
Game update: AppID 108600 "", ProcID 273, IP 0.0.0.0:0
>>> Adding process 273 for game ID 108600
GameAction [AppID 108600, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/quentin/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/quentin/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/quentin/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 108600, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/quentin/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 277 != 274, skipping destruction (fork without exec?)
>>> Adding process 274 for game ID 108600
>>> Adding process 275 for game ID 108600
>>> Adding process 276 for game ID 108600
64-bit java detected
ERROR: ld.so: object '/home/quentin/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/quentin/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 278 for game ID 108600
>>> Adding process 301 for game ID 108600
ERROR: ld.so: object '/home/quentin/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 302 for game ID 108600
Game update: AppID 108600 "", ProcID 301, IP 0.0.0.0:0
Setting breakpad minidump AppID = 108600
Steam_SetMinidumpSteamID:  Caching Steam ID:  XXXXXXXXXXXXXXX [API loaded no]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at zombie.gameStates.MainScreenState.main(MainScreenState.java:133)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 1 more
>>> Adding process 348 for game ID 108600
Game removed: AppID 108600 "", ProcID 301 

```

**Comment by pshpsh** [comment]
Same here with java games.
Rise to Ruins and Revenge of the Titans.

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.Display

**Comment by nanonyme** [comment]
Could someone re-test if adding xrandr affected this too?
