### ISSUE TITLE
Steam client don't start - No such file or directory ~/.steam/root

### ISSUE THREAD

**Issue by eIrbis** [flathub/com.valvesoftware.Steam#763]
Steam client aren't starting. Before that it was crashed. And after reboot it wasn't started
I have reinstall Steam but it wasn't help for me

**System info**
```
OS: Arch Linux x86_64  
Kernel: 5.12.5-arch1-1  
DE: Plasma 5.21.5  
CPU: Intel i5-7400 (4) @ 3.500GHz  
GPU: AMD ATI Radeon RX 580
```

**Flatpak info**
```
flatpak --version  
Flatpak 1.11.1
```

```
flatpak --gl-drivers  
default  
host  
```

**Console log:**
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam-wrapper --file-forwarding com.valvesoftware.Steam @@u %U @@  
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.8/site-packages/steam_wrapper.py", line 362, in main
    current_xdg_prefix = get_current_xdg_dir_prefix()
  File "/app/lib/python3.8/site-packages/steam_wrapper.py", line 298, in get_current_xdg_dir_prefix
    current_steam_root = os.readlink(os.path.expanduser("~/.steam/root"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/vadim/.steam/root'
```

**Comment by eIrbis** [comment]
```
flatpak run --command=bash com.valvesoftware.Steam || followed by
[📦 com.valvesoftware.Steam ~]$ ls -la
итого 24
drwxr-xr-x 1 vadim users 216 мая 23 20:08 .
drwxr-xr-x 3 vadim users  60 мая 24 09:11 ..
-rw------- 1 vadim users 188 мая 23 20:13 .bash_history
drwxr-xr-x 1 vadim users 148 мая 23 12:37 .cache
drwxr-xr-x 1 vadim users  64 мая 23 18:47 .config
drwxr-xr-x 1 vadim users 140 мая 23 19:54 .ld.so
drwxr-xr-x 1 vadim users  28 мар 27 20:55 .local
drwx------ 1 vadim users  10 мар 27 20:58 .pki
drwxr-xr-x 1 vadim users 114 мая 23 20:12 .steam
lrwxrwxrwx 1 vadim users  30 мая 23 12:30 .steampath -> /home/vadim/.steam/sdk32/steam
lrwxrwxrwx 1 vadim users  28 мая 23 12:30 .steampid -> /home/vadim/.steam/steam.pid
drwxr-xr-x 1 vadim users   6 мар 27 20:55 .var
drwxr-xr-x 1 vadim users  26 мар 27 21:23 Games
drwxr-xr-x 1 vadim users  24 мая 23 18:47 Mediateka
drwxr-xr-x 1 vadim users   0 ноя  1  2020 Pictures
lrwxrwxrwx 1 vadim users   6 мар 27 20:55 cache -> .cache
lrwxrwxrwx 1 vadim users   7 мар 27 20:55 config -> .config
lrwxrwxrwx 1 vadim users  12 мар 27 20:55 data -> .local/share
```
```
ls -la .steam/
итого 16
drwxr-xr-x 1 vadim users  114 мая 23 20:12 .
drwxr-xr-x 1 vadim users  216 мая 23 20:08 ..
-rwxr-xr-x 1 vadim users 1728 мая 23 18:45 registry.vdf
-rwxr-xr-x 1 vadim users 1728 мая 23 18:45 registry.vdf20210523184527
-rwxr-xr-x 1 vadim users 1728 мая 23 18:45 registry.vdf20210523184527
-rw-r--r-- 1 vadim users    4 мая 23 12:30 steam.pid
prw------- 1 vadim users    0 мар 27 20:55 steam.pipe
```
line 294-303 in steam_wrapper.py

```
def get_current_xdg_dir_prefix():
    if not os.path.isdir(os.path.expanduser("~/.steam")):
        logging.debug("~/.steam doesn't exists - cannot determine current prefix")
        return None
    current_steam_root = os.readlink(os.path.expanduser("~/.steam/root"))
    # FIXME we need a more reliable way to determine current prefix
    # here we assume that ~/.steam/root points to ~/.local/share/Steam
    # this will break if `steam` was first ran bypassing the wrapper
    current_prefix = os.path.normpath(os.path.join(current_steam_root, "..", "..", ".."))
    return current_prefix
```

**Comment by gasinvein** [comment]
> Should I create symbolic link ~/.steam/root -> ~/.local/share/Steam?

No, the `~/.steam` directory should be handled by Steam Client. You can delete it if you don't mind deauthenticating and losing some settings.

**Comment by eIrbis** [comment]
> > Should I create symbolic link ~/.steam/root -> ~/.local/share/Steam?
> 
> No, the `~/.steam` directory should be handled by Steam Client. You can try deleting it altogether (so that Steam wil re-create it on next launch) it if you don't mind deauthenticating and losing some settings.

Oh, thanks a lot. That solution has worked for me

**Comment by nanonyme** [comment]
Ok. Maybe it's indeed better to guide user to clean up.
