### ISSUE TITLE
Steam does not start - OSError: [Errno 95] Operation not supported: '/dev/uinput'

### ISSUE THREAD

**Issue by omcaif** [flathub/com.valvesoftware.Steam#965]
Just installed Flatpak on Gentoo, added the Flathub repository, and installed Steam with `flatpak --user install com.valvesoftware.Steam`.

When I try to run Steam, It does not start and I get the error shown in the title of the bug report:

```
$ flatpak run com.valvesoftware.Steam 
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
ERROR:root:~/.steam/root isn't a symlink to an existing directory, cannot determine current prefix
INFO:root:Will set XDG dirs prefix to /home/username/.var/app/com.valvesoftware.Steam
INFO:migration:Copying /home/username/.var/app/com.valvesoftware.Steam/config to /home/username/.var/app/com.valvesoftware.Steam/.config, ignoring set()
INFO:migration:Renaming /home/username/.var/app/com.valvesoftware.Steam/config to /home/username/.var/app/com.valvesoftware.Steam/config.old
INFO:migration:Symlinking /home/username/.var/app/com.valvesoftware.Steam/config to .config
INFO:migration:Copying /home/username/.var/app/com.valvesoftware.Steam/.local/share to /home/username/.var/app/com.valvesoftware.Steam/.local/share.bak, ignoring {'Steam'}
INFO:migration:Copying /home/username/.var/app/com.valvesoftware.Steam/data to /home/username/.var/app/com.valvesoftware.Steam/.local/share, ignoring {'Steam'}
INFO:migration:Renaming /home/username/.var/app/com.valvesoftware.Steam/data to /home/username/.var/app/com.valvesoftware.Steam/data.old
INFO:migration:Symlinking /home/username/.var/app/com.valvesoftware.Steam/data to .local/share
INFO:migration:Copying /home/username/.var/app/com.valvesoftware.Steam/cache to /home/username/.var/app/com.valvesoftware.Steam/.cache, ignoring set()
INFO:migration:Renaming /home/username/.var/app/com.valvesoftware.Steam/cache to /home/username/.var/app/com.valvesoftware.Steam/cache.old
INFO:migration:Symlinking /home/username/.var/app/com.valvesoftware.Steam/cache to .cache
INFO:root:Restarting app due to finalize sandbox tuning
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
ERROR:root:~/.steam/root isn't a symlink to an existing directory, cannot determine current prefix
INFO:root:Will set XDG dirs prefix to /home/username/.var/app/com.valvesoftware.Steam
INFO:migration:Deleting /home/username/.var/app/com.valvesoftware.Steam/config.old
INFO:migration:Deleting /home/username/.var/app/com.valvesoftware.Steam/data.old
INFO:migration:Deleting /home/username/.var/app/com.valvesoftware.Steam/cache.old
DEBUG:root:Checking input devices permissions
Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.10/site-packages/steam_wrapper.py", line 510, in main
    check_device_perms()
  File "/app/lib/python3.10/site-packages/steam_wrapper.py", line 148, in check_device_perms
    for entry in posix1e.ACL(file=uinput_path):
OSError: [Errno 95] Operation not supported: '/dev/uinput'
```

I tried using Flatseal to add `/dev/uinput:ro` to Filesystem, but that did not seem to have any effect.

**Comment by nanonyme** [comment]
@gasinvein seems like missing error handling

**Comment by gasinvein** [comment]
We probably should handle missing device node gracefully, but it's still rather uncommon host OS configuration quirk. @omcaif, what's your distro/version?

**Comment by nanonyme** [comment]
Do instead `flatpak run --command=ls com.valvesoftware.Steam -l /dev/uinput`. Those host commands aren't relared

**Comment by nanonyme** [comment]
I'm not sure if belonging to user group in host helps for having access to device node inside sandbox

**Comment by nanonyme** [comment]
I think we need to support those cases as well and check for operation not supported

**Comment by nanonyme** [comment]
If anyone has time to implement check, there are constants in Python errno module. We can check error.errno against constant and raise if it's something unexpected

**Comment by gasinvein** [comment]
@omcaif Can you please check if a test build (once it's ready) from #966 fixes the issue for you?

> I just read the traceback more carefully, and I think the problem is that I do not have ACL support in my kernel.

You're right, I didn't realize at first that `Operation not supported` indicates no ACL support, not missing device.
